using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rythin.src
{
        public enum Types {
            PRINT, PLUS, MINUS, NUMBER, CURLY_OPEN, DYNAMIC_VALUE, KEYWORD_RETURN, CURLY_CLOSE, KEYWORD_DEF, KEYWORD_INTERFACE, KEYWORD_PUBLIC_STATIC, KEYWORD_PUBLIC_NONSTATIC, KEYWORD_STATIC, KEYWORD_NONSTATIC, KEYWORD_PUBLIC, KEYWORD_PRIVATE, TYPE_STRING, STRING_LITERAL, IDENTIFIER,EQUALSCOND, TYPE_CHARSEQ, TYPE_INT, TYPE_FLOAT, TYPE_STR, TYPE_DOUBLE, TYPE_LONG,
            KEYWORD_FUNC, KEYWORD_USE, KEYWORD_CLASS, KEYWORD_ENUM, SEPARATOR, OPEN_PARENTESES, CLOSE_PARENTESES,
            EQUALS, SEMICOLON, ARROW_SET, KEYWORD_NULL, COMMENT, COLON, DOUBLE_QUOTE, EOF
    }
}
